### PR TITLE
[atspi][clippy] fixes (some) clippy noise

### PR DESCRIPTION
**Pull request by luukvanderduim**
Fix `match` on `bool` and fix an unneeded reference.
Fix cast from `i32` to `usize` using 'try_from' - breaks `AccessibleExt`s signatures. Guidance needed!
Silence Clippy on missing backticks in documentation. Not sure whether the backticks are appropriate here.

### CODE REVIEW

**Comment by DataTriny** [comment]
IMO most (if not all) of these doc comments should be replaced eventually. The only information they give is that the code was auto-generated. It's not helpful at all to anyone just wanting to write an AT.

**Comment by TTWNO** [comment]
I completely agree. Obviously, most of these docs were auto-generated themselves and it does not have detailed descriptions of very many things.

I do want to have really, really good documentation for release 1.0 of `atspi`. This is just on the back-burner for me right now. Contributions are very, very much appreciated!

**Comment by luukvanderduim** [comment]
> IMO most (if not all) of these doc comments should be replaced eventually. The only information they give is that the code was auto-generated. It's not helpful at all to anyone just wanting to write an AT.

True. I will drop the silly 'backticks commit' as these comments are not helpful anyway.

**Comment by luukvanderduim** [comment]
> I do want to have really, really good documentation for release 1.0 of `atspi`. This is just on the back-burner for me right now. Contributions are very, very much appreciated!

Fully agreed. 
The AT-SPI2 documentation landscape is fragmented. Bits and pieces scattered all over the web. It would be good if we would not repeat that. I will commit to this goal as well.

**Pull request merged**
