### PR TITLE
Add weak references among related cache items

### PR DESCRIPTION
**Pull request by samtay**
This PR adds weak refs to related cache items. Currently just parents, which could be merged as is, or we could add to children & app too.

However, with more functionality, we can't really have an apples-to-apples performance comparison. I think no matter what, we'll see a dive in benchmarks, because we are going to be doing more work to add references throughout the cache. Might need people to just try it out and see if there's any noticeable differences?

- [x] Add parent refs
- [x] Try removing complicated concurrency prioritization and just shoot off naive blocking tasks.
- [x] Add children refs
- [x] Replace traverse benchmark (that just goes up from each child to the root, which is also probably more than we should be doing in one bench!) with a complete in-order traversal. This is possible as of an earlier PR that added children to cache items.
- [x] Make other benchmarks more realistic? Maybe `reads_while_writing` shouldn't be random access, but should instead be a standard traversal?

### CODE REVIEW

**Comment by samtay** [comment]
There is a troubling initial result with this entire premise, however. While I'd expect most measurements to go downhill, since we are now doing more work up front, the one measurement that should improve is the traverse cache, which just goes up the tree, using the new weak ref if it can. However,

```
git fetch
cd cache
git checkout origin/samtay/apples-to-apples
cargo bench traverse_cache
git checkout origin/samtay/cache-parent-refs
cargo bench traverse_cache
```

shows that there is no such improvement, and there is a consistent increase of ~ 30% time to complete the operation. Note that in that bench, all of the extra work to populate references happens _outside_ of the operation being benchmarked. Should we scrap this idea @TTWNO ?

**Comment by TTWNO** [comment]
Could you try returning a `MutexGuard<_>` instead of a CacheItem. Any time a `CacheItem` is returned, we are doing a full clone. It would be much easier if we could lend out references instead. The standard library's `MutexGuard` is `!Send`, so it will not be allowed to be held across an await point. If you need that, clone it then.

**Comment by samtay** [comment]
> Could you try returning a `MutexGuard<_>` instead of a CacheItem. Any time a `CacheItem` is returned, we are doing a full clone. It would be much easier if we could lend out references instead. The standard library's `MutexGuard` is `!Send`, so it will not be allowed to be held across an await point. If you need that, clone it then.

Well, the trait method has signature `Accessible::parent(&self) -> Result<Self, _>`, so for a traversal that uses the `Accessible` methods, we'll need a clone. And on `main` and in the apples to apples comparison, we are already `clone`ing to give back a full `CacheItem`.

So, while we can offer a method that does what you suggest, it doesn't help in the general case.

**Comment by TTWNO** [comment]
I'm happy to re-write the traits. These are in `atspi`, but I know they were half-baked, so they're behind a feature flag, let me see if I can set up a generic return type that can be set by the implementer. This will take some time, so see if you can just bypass this with a custom implementation of `ref_parent()` in `impl Cacheitem { ... }` directly.

**Comment by samtay** [comment]
[63489d0](https://github.com/odilia-app/odilia/pull/101/commits/63489d01a53d229a2ed883029cbe665932252aa4) proves that we are missing tons of references that should be there.

I had a hunch that I had figured out the problem: I was thinking there might be duplicate items in the list of `cache_items` to add, which would make it so that previously inserted items (that might be weak referenced by others) would get overwritten with a _new_ `Arc<Mutex<CacheItem>>`, thus downgrading any existing weak refs. However, it appears the `wcag_items` list has no duplicates :thinking: back to the drawing board.

**Comment by samtay** [comment]
Oh man. I just realized the problem :facepalm:. We're doing the traversal with items from `Vec<CacheItem>` that are from _outside_ the cache. They never had their references populated! Fix incoming.

**Comment by TTWNO** [comment]
Nice catch! The compiler did try telling me this: "CacheItem is not of type Arc<Mutex<CacheItem>>".... I Should have known that something was up...

Again, good find. Hopefully the fix makes these benchmarks rip.

**Comment by samtay** [comment]
Ok now the only cache misses are

|item id|parent id|
|---|---|
|18698|108|
|18699|16295|

This is simply because the cache data that I logged out to `wcag_items.json` actually has these inconsistencies. That is, each of the items above specified the listed parent IDs, but those parents do _not_ specify 18698 and 18699 in their list of children. In that situation there's not much we can do, and are at the whim of the order of items inserted. But, it was 2 out of 14738 so hopefully this is a rare occurrence not worth worrying about.

**Comment by samtay** [comment]
Ok so comparing to the `samtay/apples-to-apples` without refs, we do see an increase in performance in the existing `traverse_cache` (this is the one dealing with full cloned items): time spent goes from 36ms down to 22ms. Using references over clones drops it down to 5ms. However, every other statistic deals with some writes, and they all go down in performance. Details below.

```
cache/add_all/zbus-docs time:   [3.6898 ms 3.6970 ms 3.7052 ms]
                        change: [+26.009% +26.367% +26.737%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 9 outliers among 200 measurements (4.50%)
  5 (2.50%) high mild
  4 (2.00%) high severe
cache/add/zbus-docs     time:   [6.2572 ms 6.2674 ms 6.2771 ms]
                        change: [+264.10% +265.62% +267.07%] (p = 0.00 < 0.05)
                        Performance has regressed.
Found 16 outliers among 200 measurements (8.00%)
  4 (2.00%) low severe
  12 (6.00%) low mild
cache/traverse_cache/wcag-items
                        time:   [22.410 ms 22.477 ms 22.540 ms]
                        change: [-38.321% -38.126% -37.945%] (p = 0.00 < 0.05)
                        Performance has improved.
Found 38 outliers among 200 measurements (19.00%)
  35 (17.50%) low severe
  1 (0.50%) low mild
  1 (0.50%) high mild
  1 (0.50%) high severe
cache/traverse_cache_refs/wcag-items
                        time:   [5.4315 ms 5.4373 ms 5.4440 ms]
Found 17 outliers among 200 measurements (8.50%)
  10 (5.00%) high mild
  7 (3.50%) high severe
Benchmarking cache/reads_while_writing/10: Warming up for 3.0000 s
Warning: Unable to complete 200 samples in 20.0s. You may wish to increase target time to 32.3s, enable flat sampling, or reduce sample count to 110.
cache/reads_while_writing/10
                        time:   [84.163 µs 140.23 µs 198.75 µs]
                        thrpt:  [50.316 Kelem/s 71.313 Kelem/s 118.82 Kelem/s]
                 change:
                        time:   [+37.272% +89.026% +151.23%] (p = 0.00 < 0.05)
                        thrpt:  [-60.196% -47.097% -27.152%]
                        Performance has regressed.
Found 18 outliers among 200 measurements (9.00%)
  5 (2.50%) high mild
  13 (6.50%) high severe
Benchmarking cache/reads_while_writing/100: Warming up for 3.0000 s
Warning: Unable to complete 200 samples in 20.0s. You may wish to increase target time to 34.6s, enable flat sampling, or reduce sample count to 100.
cache/reads_while_writing/100
                        time:   [110.27 µs 169.00 µs 231.21 µs]
                        thrpt:  [432.51 Kelem/s 591.71 Kelem/s 906.84 Kelem/s]
                 change:
                        time:   [+62.183% +103.54% +155.38%] (p = 0.00 < 0.05)
                        thrpt:  [-60.843% -50.870% -38.341%]
                        Performance has regressed.
Found 17 outliers among 200 measurements (8.50%)
  6 (3.00%) high mild
  11 (5.50%) high severe
Benchmarking cache/reads_while_writing/1000: Warming up for 3.0000 s
Warning: Unable to complete 200 samples in 20.0s. You may wish to increase target time to 37.8s, enable flat sampling, or reduce sample count to 100.
cache/reads_while_writing/1000
                        time:   [412.88 µs 440.99 µs 470.35 µs]
                        thrpt:  [2.1261 Melem/s 2.2676 Melem/s 2.4220 Melem/s]
                 change:
                        time:   [+69.288% +74.938% +80.845%] (p = 0.00 < 0.05)
                        thrpt:  [-44.704% -42.837% -40.929%]
                        Performance has regressed.
Found 10 outliers among 200 measurements (5.00%)
  10 (5.00%) high severe
```

**Comment by TTWNO** [comment]
Is the measurement to traverse the entire cache once, or traversing every item in the cache up to the root object. If it's the latter, I may have been worried about nothing the entire time. It's interesting though, this method decreases performance at about a 30-60% for many benchmarks due to the overhead in adding, but it decreases a net 25% to read times on my Pi4. This will be a worthwhile trade-off since read times are extremely important (especially since we can read and write without a ridiculous penalty.)

If you agree with that, let me know if you'll work on the children/app references or if I should take the reins in this week. I have a few hours this afternoon to work on Odilia so maybe I can get this done this aft.

Thank you again for your dedication and hard work on this project! All your insights have been extremely valuable, and these benchmarks will be used for a long, long time!

**Comment by TTWNO** [comment]
```text
   Compiling odilia-common v0.0.1 (/home/tait/odilia/common)
   Compiling odilia-cache v0.1.0 (/home/tait/odilia/cache)
    Finished bench [optimized] target(s) in 10m 05s
     Running unittests src/lib.rs (/home/tait/odilia/target/release/deps/odilia_cache-9e13af71e93335bc)

running 0 tests

test result: ok. 0 passed; 0 failed; 0 ignored; 0 measured; 0 filtered out; finished in 0.00s

     Running benches/load_test.rs (/home/tait/odilia/target/release/deps/load_test-934acb3d4472a887)
Gnuplot not found, using plotters backend
Benchmarking cache/add_all/zbus-docs
Benchmarking cache/add_all/zbus-docs: Warming up for 3.0000 s
Benchmarking cache/add_all/zbus-docs: Collecting 200 samples in estimated 20.216 s (400 iterations)
Benchmarking cache/add_all/zbus-docs: Analyzing
cache/add_all/zbus-docs time:   [41.854 ms 41.963 ms 42.075 ms]
                        change: [+37.603% +37.969% +38.368%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking cache/add/zbus-docs
Benchmarking cache/add/zbus-docs: Warming up for 3.0000 s
Benchmarking cache/add/zbus-docs: Collecting 200 samples in estimated 26.227 s (600 iterations)
Benchmarking cache/add/zbus-docs: Analyzing
cache/add/zbus-docs     time:   [35.165 ms 35.242 ms 35.319 ms]
                        change: [+18.301% +18.561% +18.819%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking cache/traverse_cache_refs/wcag-items
Benchmarking cache/traverse_cache_refs/wcag-items: Warming up for 3.0000 s
Benchmarking cache/traverse_cache_refs/wcag-items: Collecting 200 samples in estimated 21.097 s (600 iterations)
Benchmarking cache/traverse_cache_refs/wcag-items: Analyzing
cache/traverse_cache_refs/wcag-items
                        time:   [32.415 ms 32.456 ms 32.498 ms]
Found 6 outliers among 200 measurements (3.00%)
  6 (3.00%) high mild
Benchmarking cache/traverse_cache/wcag-items
Benchmarking cache/traverse_cache/wcag-items: Warming up for 3.0000 s

Warning: Unable to complete 200 samples in 20.0s. You may wish to increase target time to 31.2s, or reduce sample count to 120.
Benchmarking cache/traverse_cache/wcag-items: Collecting 200 samples in estimated 31.208 s (200 iterations)
Benchmarking cache/traverse_cache/wcag-items: Analyzing
cache/traverse_cache/wcag-items
                        time:   [144.94 ms 145.17 ms 145.40 ms]
                        change: [+8.6342% +8.7957% +8.9742%] (p = 0.00 < 0.05)
                        Performance has regressed.
Benchmarking cache/reads_while_writing/10
Benchmarking cache/reads_while_writing/10: Warming up for 3.0000 s
Benchmarking cache/reads_while_writing/10: Collecting 200 samples in estimated 20.842 s (1000 iterations)
Benchmarking cache/reads_while_writing/10: Analyzing
cache/reads_while_writing/10
                        time:   [13.382 ms 13.703 ms 14.020 ms]
                        thrpt:  [713.25  elem/s 729.76  elem/s 747.28  elem/s]
                 change:
                        time:   [+32.322% +38.556% +45.266%] (p = 0.00 < 0.05)
                        thrpt:  [-31.161% -27.827% -24.427%]
                        Performance has regressed.
Benchmarking cache/reads_while_writing/100
Benchmarking cache/reads_while_writing/100: Warming up for 3.0000 s
Benchmarking cache/reads_while_writing/100: Collecting 200 samples in estimated 20.802 s (1000 iterations)
Benchmarking cache/reads_while_writing/100: Analyzing
cache/reads_while_writing/100
                        time:   [13.800 ms 14.113 ms 14.416 ms]
                        thrpt:  [6.9365 Kelem/s 7.0858 Kelem/s 7.2462 Kelem/s]
                 change:
                        time:   [+30.653% +36.558% +43.093%] (p = 0.00 < 0.05)
                        thrpt:  [-30.116% -26.771% -23.461%]
                        Performance has regressed.
Found 1 outliers among 200 measurements (0.50%)
  1 (0.50%) low mild
Benchmarking cache/reads_while_writing/1000
Benchmarking cache/reads_while_writing/1000: Warming up for 3.0000 s
Benchmarking cache/reads_while_writing/1000: Collecting 200 samples in estimated 21.371 s (1000 iterations)
Benchmarking cache/reads_while_writing/1000: Analyzing
cache/reads_while_writing/1000
                        time:   [14.179 ms 14.507 ms 14.828 ms]
                        thrpt:  [67.438 Kelem/s 68.934 Kelem/s 70.528 Kelem/s]
                 change:
                        time:   [+31.563% +37.372% +43.865%] (p = 0.00 < 0.05)
                        thrpt:  [-30.490% -27.205% -23.991%]
                        Performance has regressed.
Found 1 outliers among 200 measurements (0.50%)
  1 (0.50%) low mild
```

**Comment by TTWNO** [comment]
Not sure why the improvement is marginal instead of an order of magnitude or two faster, but that's an issue for future Tait, lol!

**Comment by samtay** [comment]
No need, I will push up children refs soon! I've just been revising some benchmarks so that we can see the difference it makes. I'm also going to update the current parent traversals to just start from leaves instead of starting at every node (I agree that that's too much for a single measurement).

**Comment by TTWNO** [comment]
Just so you know, the latest commit seems to hang on the benchmark `cache/reads_while_writing/10; can't figure out why that is. Perhaps we hand out an dropped reference earlier in the tests.

**Comment by samtay** [comment]
> Just so you know, the latest commit seems to hang on the benchmark `cache/reads_while_writing/10; can't figure out why that is. Perhaps we hand out an dropped reference earlier in the tests.

Yup, pretty sure there's a deadlock, looking into it

**Comment by samtay** [comment]
Full disclosure, I'm not really getting much signal that we've materially improved things with children references. The measurements seem pretty noisy: `git checkout 0a83a1c27076213aafcedb485634c04a7b2d8542 ; cargo bench ; git checkout samtay/cache-parent-refs ; cargo bench`. 

I'm gonna unmark the draft though and leave it up to you if you want to merge!

**Comment by TTWNO** [comment]
Adding children references won't materially improve our existinf benchmarks.

But, one test I'd like to get in eventually is a structural navigation test. Once there is an iteratoe/stream that can walk though the tree the way structural navigation would, we can test for that. This is a more realistic benchmark as to the delay a user will feel when navigating around a webpage, for example.

Anyways, I'll review all the changes and get this merged soon.

**Comment by samtay** [comment]
You'll see when you review, but I added a structural nav test - just a really basic recursive depth first traversal, not with custom iterators. The command above will show the difference between structural nav before & after children refs.

For sure the laziness of an iterator would be the way to go though, with much less memory usage (otherwise all the children get collected into vecs eagerly). I've gotta write up my project today but I may take a peek at that and see if I can squeeze it into this PR.

**Comment by TTWNO** [comment]
You can let me deal with CI if you'd like.

**Comment by samtay** [comment]
Just realized something: our `reads_while_writing` benches are a little misleading at the moment. We should have been cloning an empty cache in the setup operation; as is, we're using the same one throughout, so the write operations are just re-adding existing elements and the reads are simply reading elements that exist already. (Also criterion first runs the operation once to estimate time to completion, so all of the measurements are performed with a cache that has all the items already.)

It's not necessarily an unreasonable thing to measure, but also not what I intended. 6fee26a changes this to measure "successful reads of new items, as they are written to the cache". Luckily the measurements are still extremely fast.

**Comment by TTWNO** [comment]
I am very happy with the performance seen with these changes. In particular, on desktop, I can see that `cache/traverse_up_refs/wcag-items` (1.3ms, 18.6ms) beats `cache/traverse_up/wcag-items` (17.1ms, 222ms) by just over an order of magnitude on the Pi and desktop respectively. Well done here!
I think the next step is creating a streaming async iterator. I might be able to do this.

Let's get this merged, and we'll add additional functionality from here. Thanks again for your great and mighty contributions! If I'm ever in your city, please allow me to buy you a nice beer (or other beverage of choice)! I truly couldn't do this work alone.

Also, you can ignore the `*-gnu` tests... they're running out of RAM to compile Odilia, lol!

**Pull request merged**
