### PR TITLE
add notification reading support

### PR DESCRIPTION
**Pull request by albertotirla**
this uses the odilia-notify crate in order to provide odilia with the ability of monitoring the bus, and then hooks the result in the speech framework

the code isn't currently the most robust, but it does the job relatively well

for example, it seemns that many apps don't provide a non-empty string for app_name, a thing this currently doesn't handle

### CODE REVIEW

**Comment by albertotirla** [comment]
apparently, the clippy test is failing because of something this pr didn't touch at all, so other prs should have failed on this as well. Should I merge this now? opinions?

**Comment by TTWNO** [comment]
Should this really be implemented by sniffing the bus?

I was under the assumption that notification daemons will put information in a live area that screen readers will pick up?

Advantage of this approach is you don't need a notification daemon (or rather, that your screen reader *becomes* the notification daemon), but the downside is that if you're using an existing (and accessible) notification daemon, then you will be getting data from both sources.

Do you have plans to mitigate this problem?

**Comment by albertotirla** [comment]
@TTWNO well, it's not precisely a specific accessible region where demons put their notifications. In stead, it's another orca hack, which, as far as I was able to read, envolves monitoring if a new window appeared and its role is alert, or notification, or something like that, I'm a bit fuzzy on the details
but the advantage of this is that, essentially, even if you're in a minimal environment with, say, swaybar as your dock and notifications demon, it won't display anything through any accessibility API. So, in this instance, as long as the xdg notifications interface is still supported which I'm not really sure of in the long run, this method should work irrespective of the daemon being used.
as to information being repeated twice, odilia already doesn't read notifications, and as long as we don't implement the hack that orca implements, we shouldn't get the notifications output

**Comment by TTWNO** [comment]
> as long as the xdg notifications interface is still supported which I'm not really sure of in the long run, this method should work irrespective of the daemon being used.

Oh I'm not worried. For better or worse, DBus, and XDG portals are becoming the standard. So fair enough, I get your point. I never knew this was another Orca hack :laughing: 

Tried it out on my local machine, it it works fine... I want to see a better criticality and app indicators (since right now it does not do either). Thoughts? I don't need anything advanced, but it might be nice to get the app name, criticality level (if supplied), then also say the text.

**Comment by albertotirla** [comment]
@TTWNO if you want, you can look at my previous commits, where I tryed doing that. The commit where I changed it is clearly labeled, and the description says that most apps, especially gtk ones, don't provide anything but an empty string in the app_name argument, so we don't know exactly where a notification comes from, maybe try app_icon instead? more experimentation is needed, and feel free to reintroduce that bit of code if you feel like testing with different toolkits. About urgency, I dk, is that even listed in the spec?
on gnome, I noted there, there is the possibility of using the org.gtk.notifications interface, because that's what apps use to communicate directly with the shell, bypassing the general xdg channels, so possible our solution may not work there, but when I monitored it, I saw notifications sent through there which weren't displayed in shell, namely when a file was coppied in the file manager. So, I do believe that's a kinda interprocess pubsub system for interconnected gnome components, including gtk apps. That being said, the process of monitoring org.gtk.notifications as well is relatively simple to do, but since I rarely use gnome, I wouldn't be the best person to implement it, as the apps send notifications via that interface and the path /org/gtk/notifications only when shell is detected.
I wish there was a better way of doing this, but unfortunately there isn't an accessibility specific API, and since snooping on notifications is actively tried to be prohibited, we're stuck in a very hard place between are we providing anything at all for our users, even if we sacrifice a bit of security, or are we doing nothing, waiting for all the components to fall in place? very, very hard place that is indeed

**Pull request merged**
