### PR TITLE
Add benchmark for the cache

### PR DESCRIPTION
**Pull request by samtay**
## questions

1. Does any part of odilia actually _read_ from the cache yet? The closest I can find is a [calls to `cache.get_or_create`](https://github.com/odilia-app/odilia/blob/d22fb8d650463a816527a245e92a2fb4a50a6d4b/odilia/src/events/object.rs) when `ObjectEvents::TextChanged` is dispatched - but these all appear to be done with the intention of _writing_ to the cache.

2. There's currently no way to get children from the cache item; is this intended? For now, my `traversal_cache` benchmark just goes in one direction, from a child upwards to the root.

3. One of the stated goals for odilia to be fast was that we want to be able to traverse the accessibility tree even when it hasn't been fully written. This isn't possible with the current cache; the entire cache is behind an `RwLock`, so if a page loads and begins writing to it (via `add_all`), no one can read from it (via `get`) until the write is finished. I assume that this is undesirable?

4. Anyone know why [`events::document::load_complete`](https://github.com/odilia-app/odilia/blob/d22fb8d650463a816527a245e92a2fb4a50a6d4b/odilia/src/events/document.rs#L9-L39) adds all the cache items twice? I printed out the items before and after and diffed them, and they _are_ slightly different but its such a massive blob of items, I couldn't readily spot it. (If no one knows I could do a json print and json-diff to figure this out.)

## next up, perhaps

- [x] Allow reads while write is still in progress
- Add the weak ref to parent items for faster traversal (as suggested by tait)

### CODE REVIEW

**Comment by samtay** [comment]
Ah I see; I missed the other open PR. Looks like the answer to question (1) is, not yet, but after #86 ([call to `cache.get`](https://github.com/odilia-app/odilia/pull/86/files#diff-e412a4b8d97251c5243da3bae787ef9c134c5ceeeb763cb42cde94e03f728f54R216-R217)).

We can certainly prioritize that PR. Looks like only minor adjustments will be needed to the benchmark after it merges.

**Comment by TTWNO** [comment]
1. This is the only place for now. There are a lot of changes to `atspi` and the cache itself that I want solved before we start reading from the cache. For example, right now, you can not treat a `CacheItem` the same way you would an `AccessibleProxy` because you don't have the same methods you can call on them. The other Odilia PR has that branch of atspi set up but it's just not implemented yet.
3. Not intended, but 100% correct. Children are not referenced or stored in the cache.
4. get_or_create will either get the item from the cache, or create that item in the cache, then return it—this call, in theory should usualy be cheap since I expect Odilia to have more-or-less the entire tree in memory.
5. Not sure what you're talkimg about here. It adds it to a vector, then adds thw entire vector to the cache. Perhaps we should write to the cache one at a time?

**Comment by TTWNO** [comment]
If you want to be able to read and write at the same time, we either need to change to a crate like `evmap` for eventual consistency maps (which we removed due to difficulty is supported data structures), or find some other eventually consistent data structure implementation in Rust.

I am open to ideas, but we had a lot of trouble we `evmap` and I don't want to repeat our same problems.

**Comment by samtay** [comment]
For 4, to be more specific, it does this:

```rust
let entire_cache = cache.get_items().await?;
let mut cache_items = Vec::new();
for item in entire_cache {
cache_items.push({essentially build CacheItem from item})
}
state.cache.add_all(cache_items).await;
```

Oh wait, I think I see. Is the `cache` and `entire_cache` coming from some atspi source, and then we're essentially copying all those items into our local `state.cache`? 

As for concurrent reads/writes, I'm more asking what _you_ want :smile:. I think bgt-lover specified elsewhere in the chat a desire to not have to hang and be unresponsive when a new tree is loaded up. So I was thinking that it would be necessary to allow some concurrent reads while writes are still under way. Looking at `evmap`, I agree its API is sort of unnecessarily clunky :confused: .. maybe it wouldn't be so bad to wrap those read/write handles into a single struct that could be passed around. Or, at the very least, keep those implementation details from leaking outside of the `cache` crate. I'll play around with it. I also wonder if dashmap would make sense.

**Comment by TTWNO** [comment]
> Oh wait, I think I see. Is the cache and entire_cache coming from some atspi source, and then we're essentially copying all those items into our local state.cache?

Correct.

And yes, I'd be fine loading items individually so that users can still use `get/get_or_create` while a giant tree is loading into the cache. An individual item won't take long (in CPU time), so as long as there's an unlock between each addition, the SR shouldn't lock up.

**Comment by TTWNO** [comment]
Sending a PR to your branch here with some changes to be up to date with the latest atspi.

**Comment by samtay** [comment]
> Sending a PR to your branch here with some changes to be up to date with the latest atspi.

I'm happy to do this myself, I was just updating locally and realized that the json is out of date now, which might be annoying to regenerate.

**Comment by TTWNO** [comment]
I think I can write a script to maks them valid. Let's see...

**Comment by TTWNO** [comment]
Done! Check the latest commit on my PR to your PR, heehee!

**Comment by TTWNO** [comment]
Nice catch!

**Comment by TTWNO** [comment]
Would you like me to merge or are you still working on this?

Also can you explain the cargo bench output to me, I'm not sure I fully understabd it.

**Comment by samtay** [comment]
Hey @TTWNO yep this would be a good time to merge! I've got other improvements that will go in the next PR. Also see my answer in matrix for the cargo bench output.

**Comment by TTWNO** [comment]
My bad, my Matrix must be down.

**Pull request merged**
